spring.application.name=api

# Banco de Dados (PostgreSQL + PostGIS)
# O Spring vai substituir isso pelas vari�veis do seu .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ... (Mantenha o resto das configura��es do JPA e PostGIS que j� estavam aqui) ...
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081